name: knudge_test
channels:
  - conda-forge
  - defaults
dependencies:
  - atk-1.0=2.38.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - graphite2=1.3.13
  - graphviz=8.1.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=8.2.1
  - icu=73.2
  - idna=3.4
  - lerc=4.0.0
  - libabseil=20230802.1
  - libcxx=16.0.6
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libglib=2.78.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libpng=1.6.39
  - libprotobuf=4.24.4
  - librsvg=2.56.3
  - libsqlite=3.40.0
  - libtiff=4.6.0
  - libtool=2.4.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.11.5
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.4
  - pango=1.50.14
  - pcre2=10.40
  - pip=22.3.1
  - pixman=0.42.2
  - protobuf=4.24.4
  - pysocks=1.7.1
  - python=3.10.8
  - python_abi=3.10
  - readline=8.1.2
  - setuptools=65.5.1
  - tiktoken=0.5.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.3.0
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - appnope==0.1.3
      - argparse==1.4.0
      - arxiv-latex-cleaner==0.1.30
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - asyncio==3.4.3
      - attrs==22.1.0
      - automat==22.10.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bert-score==0.3.12
      - bibtexparser==1.4.0
      - bs4==0.0.1
      - cached-property==1.5.1
      - certifi==2022.12.7
      - cffi==1.15.1
      - charset-normalizer==2.1.1
      - click==8.1.3
      - colorama==0.4.6
      - comm==0.1.2
      - constantly==15.1.0
      - contourpy==1.0.6
      - cryptography==39.0.0
      - cssselect==1.2.0
      - cycler==0.11.0
      - dataclasses-json==0.6.1
      - datasets==2.7.1
      - debugpy==1.6.4
      - decorator==5.1.1
      - dill==0.3.6
      - diskcache==5.4.0
      - docker==5.0.0
      - entrypoints==0.4
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - filelock==3.8.2
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2022.11.0
      - greenlet==3.0.0
      - h11==0.14.0
      - httpcore==0.12.3
      - httpx==0.16.1
      - huggingface-hub==0.11.1
      - hyperlink==21.0.0
      - incremental==22.10.0
      - iniconfig==2.0.0
      - ipykernel==6.19.2
      - ipython==8.7.0
      - itemadapter==0.8.0
      - itemloaders==1.1.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsons==1.6.3
      - jupyter-client==7.4.8
      - jupyter-core==5.1.0
      - kiwisolver==1.4.4
      - langchain==0.0.311
      - langsmith==0.0.43
      - latexcodec==2.0.1
      - logzero==1.7.0
      - lxml==4.9.2
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.6
      - more-itertools==9.0.0
      - multidict==6.0.3
      - multiprocess==0.70.14
      - mypy-extensions==1.0.0
      - nest-asyncio==1.5.6
      - nltk==3.8.1
      - numpy==1.23.5
      - openai==0.28.1
      - overrides==3.1.0
      - packaging==22.0
      - pandas==1.5.2
      - parsel==1.8.1
      - parso==0.8.3
      - pdfminer-six==20221105
      - pdfplumber==0.7.6
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.3.0
      - platformdirs==2.6.0
      - pluggy==0.13.1
      - portalocker==2.7.0
      - prompt-toolkit==3.0.36
      - protego==0.3.0
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py==1.11.0
      - pyarrow==10.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybtex==0.24.0
      - pycountry==22.3.5
      - pycparser==2.21
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pydispatcher==2.0.7
      - pydot==1.4.2
      - pygments==2.13.0
      - pylatexenc==2.10
      - pyopenssl==23.2.0
      - pyparsing==3.0.9
      - pytest==6.2.4
      - python-dateutil==2.8.2
      - graphviz
      - pytz==2022.6
      - pyyaml==6.0
      - pyzmq==24.0.1
      - queuelib==1.6.2
      - rank-bm25==0.2.2
      - rebiber==1.1.3
      - redis==4.4.2
      - regex==2022.10.31
      - repro==0.1.4
      - requests==2.28.1
      - requests-file==1.5.1
      - responses==0.18.0
      - rfc3986==1.5.0
      - rouge-score==0.1.2
      - sacrebleu==2.3.1
      - sacremoses==0.0.53
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - scrapy==2.11.0
      - scrapy-wayback-machine==1.0.3
      - seaborn==0.12.2
      - sentencepiece==0.1.99
      - service-identity==23.1.0
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - spotipy==2.22.0
      - sqlalchemy==2.0.21
      - stack-data==0.6.2
      - tabulate==0.9.0
      - tenacity==8.2.3
      - termcolor==2.2.0
      - threadpoolctl==3.2.0
      - tldextract==3.6.0
      - tokenizers==0.13.2
      - toml==0.10.2
      - torch==1.13.1
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.7.1
      - transformers==4.25.1
      - tsv==1.2
      - twisted==22.10.0
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - typish==1.9.3
      - unidecode==1.3.6
      - urllib3==1.26.13
      - w3lib==2.1.2
      - wand==0.6.11
      - wayback-machine-scraper==1.0.8
      - wcwidth==0.2.5
      - websocket-client==1.5.1
      - xlwt==1.3.0
      - xxhash==3.1.0
      - yarl==1.8.2
      - zope-interface==6.0
